from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors
from datetime import datetime
import os

def generate_session_report(session_data, user_data, output_dir="reports"):
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
    
    filename = f"{output_dir}/report_{user_data['id']}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    
    doc = SimpleDocTemplate(filename, pagesize=letter)
    story = []
    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=18,
        textColor=colors.HexColor('#1a73e8'),
        spaceAfter=30
    )
    
    story.append(Paragraph("Swasthya Bandhu - Health Assessment Report", title_style))
    story.append(Spacer(1, 0.2*inch))
    
    patient_info = [
        ["Patient Name:", user_data['name']],
        ["Age:", str(user_data['age'])],
        ["Gender:", user_data['gender']],
        ["Date:", datetime.now().strftime('%Y-%m-%d %H:%M')],
    ]
    
    t = Table(patient_info, colWidths=[2*inch, 4*inch])
    t.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(t)
    story.append(Spacer(1, 0.3*inch))
    
    story.append(Paragraph("<b>Symptoms Described:</b>", styles['Heading2']))
    story.append(Paragraph(session_data['symptom_input'], styles['BodyText']))
    story.append(Spacer(1, 0.2*inch))
    
    assessment_data = [
        ["Severity Score:", f"{session_data['severity_score']}/10"],
        ["Urgency Level:", session_data['urgency']],
        ["Recommended Specialist:", session_data['recommended_specialist']],
    ]
    
    story.append(Paragraph("<b>Assessment:</b>", styles['Heading2']))
    t2 = Table(assessment_data, colWidths=[2.5*inch, 3.5*inch])
    t2.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ]))
    story.append(t2)
    story.append(Spacer(1, 0.2*inch))
    
    if session_data.get('risk_factors'):
        story.append(Paragraph("<b>Risk Factors:</b>", styles['Heading2']))
        for rf in session_data['risk_factors']:
            story.append(Paragraph(f"• {rf}", styles['BodyText']))
        story.append(Spacer(1, 0.2*inch))
    
    if session_data.get('suggested_tests'):
        story.append(Paragraph("<b>Suggested Diagnostic Tests:</b>", styles['Heading2']))
        for test in session_data['suggested_tests']:
            story.append(Paragraph(f"• {test}", styles['BodyText']))
        story.append(Spacer(1, 0.2*inch))
    
    if session_data.get('differential_diagnoses'):
        story.append(Paragraph("<b>Possible Conditions:</b>", styles['Heading2']))
        for diag in session_data['differential_diagnoses']:
            story.append(Paragraph(f"• {diag}", styles['BodyText']))
        story.append(Spacer(1, 0.2*inch))
    
    disclaimer = """<b>DISCLAIMER:</b> This report is generated by an AI-powered health assessment system 
    and is NOT a final medical diagnosis. It is intended to assist in preliminary health evaluation only. 
    Please consult with a qualified healthcare professional for proper diagnosis and treatment."""
    
    story.append(Spacer(1, 0.3*inch))
    story.append(Paragraph(disclaimer, styles['BodyText']))
    
    doc.build(story)
    return filename
