import { useState } from 'react'
import { Card, Button, Typography, Spin, Alert, Divider, Tag, Row, Col } from 'antd'
import { FileTextOutlined, DownloadOutlined } from '@ant-design/icons'
import api from '../../services/api'

const { Title, Paragraph, Text } = Typography

export default function GovernmentReport() {
  const [loading, setLoading] = useState(false)
  const [report, setReport] = useState<any>(null)
  const [error, setError] = useState<string | null>(null)

  const generateReport = async () => {
    setLoading(true)
    setError(null)
    try {
      const response = await api.post('/admin/generate-government-report')
      setReport(response.data)
    } catch (err: any) {
      setError(err.response?.data?.detail || 'Failed to generate report')
    } finally {
      setLoading(false)
    }
  }

  const downloadReport = () => {
    if (!report) return
    
    const content = `
GOVERNMENT HEALTH REPORT
Generated by: Swasthya Bandhu Healthcare Platform
Date: ${new Date(report.report_generated_at).toLocaleString()}
Period: ${report.report_period}

===========================================
DATA SUMMARY
===========================================

Platform Overview:
- Total Patients: ${report.data_summary.platform_overview.total_patients}
- Total Doctors: ${report.data_summary.platform_overview.total_doctors}
- Total Appointments: ${report.data_summary.platform_overview.total_appointments}

Health Trends (Last 30 Days):
- Total Consultations: ${report.data_summary.health_trends.total_consultations}
- Low Severity: ${report.data_summary.health_trends.severity_distribution.low}
- Moderate Severity: ${report.data_summary.health_trends.severity_distribution.moderate}
- High Severity: ${report.data_summary.health_trends.severity_distribution.high}
- Emergency Cases: ${report.data_summary.health_trends.severity_distribution.emergency}

Active Outbreaks: ${report.data_summary.outbreak_alerts.length}

===========================================
AI ANALYSIS & RECOMMENDATIONS
===========================================

${report.ai_analysis}

===========================================
END OF REPORT
===========================================
`
    
    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `government-health-report-${new Date().toISOString().split('T')[0]}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="min-h-screen bg-gray-50 p-6">
      <div className="max-w-6xl mx-auto">
        <Card>
          <div className="flex justify-between items-center mb-6">
            <div>
              <Title level={2}>
                <FileTextOutlined className="mr-2" />
                Government Health Report
              </Title>
              <Paragraph className="text-gray-600">
                AI-powered comprehensive analysis of platform health data for government authorities
              </Paragraph>
            </div>
            <Button
              type="primary"
              size="large"
              onClick={generateReport}
              loading={loading}
              icon={<FileTextOutlined />}
            >
              Generate Report
            </Button>
          </div>

          {error && (
            <Alert
              message="Error"
              description={error}
              type="error"
              showIcon
              closable
              className="mb-4"
            />
          )}

          {loading && (
            <div className="text-center py-12">
              <Spin size="large" />
              <Paragraph className="mt-4 text-gray-600">
                Analyzing platform data and generating comprehensive report...
              </Paragraph>
            </div>
          )}

          {report && !loading && (
            <div>
              <Alert
                message="Report Generated Successfully"
                description={`Generated on ${new Date(report.report_generated_at).toLocaleString()}`}
                type="success"
                showIcon
                className="mb-4"
                action={
                  <Button
                    size="small"
                    type="primary"
                    icon={<DownloadOutlined />}
                    onClick={downloadReport}
                  >
                    Download
                  </Button>
                }
              />

              <Divider orientation="left">Platform Statistics</Divider>
              
              <Row gutter={[16, 16]} className="mb-6">
                <Col xs={24} sm={12} md={6}>
                  <Card className="text-center">
                    <Title level={3} className="!mb-0">
                      {report.data_summary.platform_overview.total_patients}
                    </Title>
                    <Text className="text-gray-600">Total Patients</Text>
                  </Card>
                </Col>
                <Col xs={24} sm={12} md={6}>
                  <Card className="text-center">
                    <Title level={3} className="!mb-0">
                      {report.data_summary.platform_overview.total_doctors}
                    </Title>
                    <Text className="text-gray-600">Total Doctors</Text>
                  </Card>
                </Col>
                <Col xs={24} sm={12} md={6}>
                  <Card className="text-center">
                    <Title level={3} className="!mb-0">
                      {report.data_summary.health_trends.total_consultations}
                    </Title>
                    <Text className="text-gray-600">Consultations (30d)</Text>
                  </Card>
                </Col>
                <Col xs={24} sm={12} md={6}>
                  <Card className="text-center">
                    <Title level={3} className="!mb-0">
                      {report.data_summary.outbreak_alerts.length}
                    </Title>
                    <Text className="text-gray-600">Active Outbreaks</Text>
                  </Card>
                </Col>
              </Row>

              <Divider orientation="left">Severity Distribution</Divider>
              
              <div className="flex gap-4 mb-6">
                <Tag color="green">
                  Low: {report.data_summary.health_trends.severity_distribution.low}
                </Tag>
                <Tag color="orange">
                  Moderate: {report.data_summary.health_trends.severity_distribution.moderate}
                </Tag>
                <Tag color="red">
                  High: {report.data_summary.health_trends.severity_distribution.high}
                </Tag>
                <Tag color="purple">
                  Emergency: {report.data_summary.health_trends.severity_distribution.emergency}
                </Tag>
              </div>

              {report.data_summary.outbreak_alerts.length > 0 && (
                <>
                  <Divider orientation="left">Active Outbreak Alerts</Divider>
                  <div className="space-y-2 mb-6">
                    {report.data_summary.outbreak_alerts.map((outbreak: any, idx: number) => (
                      <Alert
                        key={idx}
                        message={`${outbreak.region} - ${outbreak.cases} cases`}
                        description={`Symptoms: ${Array.isArray(outbreak.symptoms) ? outbreak.symptoms.join(', ') : outbreak.symptoms}`}
                        type={outbreak.severity === 'high' ? 'error' : 'warning'}
                        showIcon
                      />
                    ))}
                  </div>
                </>
              )}

              <Divider orientation="left">AI Analysis & Recommendations</Divider>
              
              <Card className="bg-blue-50">
                <div style={{ whiteSpace: 'pre-wrap', lineHeight: '1.8' }}>
                  <Text>{report.ai_analysis}</Text>
                </div>
              </Card>
            </div>
          )}

          {!report && !loading && (
            <div className="text-center py-12">
              <FileTextOutlined style={{ fontSize: 64, color: '#d9d9d9' }} />
              <Paragraph className="mt-4 text-gray-600">
                Click "Generate Report" to create a comprehensive health analysis for government authorities
              </Paragraph>
            </div>
          )}
        </Card>
      </div>
    </div>
  )
}
